### ISSUE TITLE
How use it ?

### ISSUE THREAD

**Issue by jmd87fr** [moodlerooms/moodle-theme_snap#1]
Hi 
I want to test your new wonderfull theme ;-) 
i downloaded the zip folder 
unzip and rename as 'snap' 
put the folder 'snap' in /MyMoodle28/theme/
In MyMoodle28  block administration > Site Administration > Appearance > Themes  ..  no 'snap' only 'clean' and 'more'
May be i made a mistake ?
Could you help me please ?

**Comment by mrmark** [comment]
Did you visit Site Administration > Notifications with an admin user to install the theme?  Other problems that come to mind is that it could be a caching issue.  Could try purging caches and then visiting Notifications.

**Comment by jmd87fr** [comment]
Yes of course !  But the new theme don't appear in 'notification' ? 
I'l a newbie whith git ;-) may be i made something wrong ?

**Comment by stuartlamour** [comment]
Glad you got it all working, let us know if you find anything untoward.
