### ISSUE TITLE
Problem with folder resource on Snap theme

### ISSUE THREAD

**Issue by thauska** [moodlerooms/moodle-theme_snap#109]
I have seen one problem on snap theme. I can't create new folder into the folder resource. How can I fix this?

**Comment by thauska** [comment]
Someone?

**Comment by daveyboond** [comment]
It seems OK on my Snap - add folder resource, save and display, click Edit button, then click the 2nd button under 'Files' at top left to add a folder.

That's all on Moodle 3.4, using latest commit on master branch of Snap.

**Comment by thauska** [comment]
I have download the snap theme from moodle org. The issue for this folder is resolve.
