### ISSUE TITLE
Incorrect mouse hover tooltips

### ISSUE THREAD

**Issue by mudrd8mz** [moodlerooms/moodle-theme_snap#12]
It seems to me that the mouse cursor hover tooltips for the user menu and the navigation hamburger are swapped. Hovering the hamburger displays my user name as the tool tip. Hovering the user menu gives "Site navigation".

![tooltips](https://cloud.githubusercontent.com/assets/85831/8861800/abb3b29e-318c-11e5-97dd-06920ac24eb8.png)

**Comment by stuartlamour** [comment]
Hi David,

the tooltip says admin because it is a link to the admin block.

Cheers
Stuart

**Comment by mudrd8mz** [comment]
Ah, sorry. I was logged in as the site admin with that name and that confused me. All right then.
