### ISSUE TITLE
Question regarding fonts license

### ISSUE THREAD

**Issue by mudrd8mz** [moodlerooms/moodle-theme_snap#13]
Hi guys,

may I ask for clarification of the source and license of the fonts used in the theme's `fonts` directory. Do I get it right that the glyphicons-halflings there are those that are part of the bootstrap? And what about line-icons?

May I ask for adding a file like README or moodle_readme.txt into the fonts folder that would explicitly refer to the font's source and their license?

Before approving the theme in the Moodle plugins directory, we must make sure that it is legal to distribute the theme's ZIP package under GPLv3. Thanks for understanding.

**Comment by stuartlamour** [comment]
Hi David, 

thanks for the comment - i've done a few test and found removing the icon fonts and replacing the ones used with svgs speeds up snap.

We don't use the bootstrap glyphicons in snap so can remove those and let other plugins include when they need them.

We have a version schedule in moodlerooms and the next update will be mid october, so will update this issue once that is all publicly available when the open source branch will update with my changes.

Cheers
Stuart Lamour

**Comment by davidscotson** [comment]
We've added a licence file to the folder which links to the Bootstrap 3 github where the original open source font files where downloaded. With the deletion of the other files, hopefully that clarifies all the font related issues.
