### ISSUE TITLE
Ie8- Login and Personal menu popups

### ISSUE THREAD

**Issue by Ankhesa** [moodlerooms/moodle-theme_snap#14]
Hi, I'm trying to figure out why IE8 will not open popups link (Loguin and personal menu). Can you help a little with this.
Thank You!

**Comment by stuartlamour** [comment]
Hi Ankhesa,

I'm afraid moodle doesn't support ie8.

https://docs.moodle.org/dev/Moodle_2.7_release_notes#Browser_support

**Comment by stuartlamour** [comment]
Looks like microsoft are ending support for ie8 in January.
