### ISSUE TITLE
Moodle Version Support

### ISSUE THREAD

**Issue by matthewbassett** [moodlerooms/moodle-theme_snap#15]
I feel like a bit of a dunce for asking this question, because I am sure the information is somewhere, but what versions of moodle is the SNAP theme compatible with?

**Comment by stuartlamour** [comment]
Hi Matthew, 

at moodlerooms we normally update 6 months after an official moodle version - mainly to give core time to iron out any bugs and just ensure the version is stable.

Right now that mean Snap is optimised for 2.8, at the end of December 2015 we will be releasing the 2.9 version and in the summer of 2016 the 3.0 version.

You're more than welcome to try Snap with any version and let us know if what you find!

Cheers
Stuart

**Comment by derekc** [comment]
Stuart, we upgrade each year in the January break to the latest version (in this year, Moodle 3.0)
This means Snap with your release schedule is not really useful.

How does GIT work?  Can you set up a branch to play with, specifically labelled BETA?
Do you expect a lot of work needed to go from 2.9 o 3.0?

-Derek

**Comment by stuartlamour** [comment]
Hi Derek,

moodle 3.0 isn't release yet, so it's difficult to predict if there will be anything big changes needed.

2.9 has lots of changes in with the new page for students to access their grades, the new profile and preferences page and other things in the release notes https://docs.moodle.org/dev/Releases#Moodle_2.9

You're more than welcome to try snap with 3.0 once it's released and let us know anything you find!

Cheers
Stuart

**Comment by derekc** [comment]
Update:
With a recent 3.0 Beta, seems to be looking good.  I have had some glitches unrelated to Snap, so install it all again after 3.0 comes out and I'll report back.

I think you guys are way too conservative.  When there are not HUGE changes in an upgrade, with the new way HQ is running things, things usually settle down in a few months or less.

I'm interested in your top navigation option.  Looks good.

-Derek

**Comment by davidscotson** [comment]
Thanks for testing that out for us, we do tend to err on the side of caution, as you can never be sure that everything is fine until you find the time to test it thoroughly, but people trying it out on their test sites is one of the best ways to be sure there aren't any major bugs, and to find and fix any problems, so thanks again and please let us know if you spot any issues.

**Comment by matthewbassett** [comment]
Hi all, just checking in again to see if there is any word on the 2.9 release date? I'm still seeing 2.7 and 2.8, but no 2.9 yet q:
Sorry to be a pain, I'm getting antsy q:

**Comment by stuartlamour** [comment]
2.9 is out so closing this - please feel free to open issues for 3.0!
