### ISSUE TITLE
Install Naming Issue

### ISSUE THREAD

**Issue by derekc** [moodlerooms/moodle-theme_snap#16]
I downloaded the zip but got this error during install.

![snap plugin](https://cloud.githubusercontent.com/assets/687780/10752268/8f63162e-7cec-11e5-80a3-ed9a3be98da6.png)

-Derek

**Comment by stuartlamour** [comment]
Hi Derek,

the folder in your themes directory should be called the theme name - in this case snap.

I sometimes get caught out be this too when i download new themes :)

Cheers
Stuart
