### ISSUE TITLE
Menu on frontpage

### ISSUE THREAD

**Issue by cb526** [moodlerooms/moodle-theme_snap#17]
Hi there,
Thank you for developing such a beautiful and unique theme. Moodle is like a different LMS with this theme applied and I hope to implement it on our site before the start of the next academic year
.
A strange issue I'm having is that the menu won't work on the front page. The link appears [siteurl/#inst5] but nothing happens at all. I've tried it on various browsers and on mobile but no joy. The menu works perfectly fine on other pages however. To turn editing on on the front page, I need to access a course page, turn editing on there, and then return to the front page. Same for site admin etc - can't access it from the front page.

I'm not a developer but if there's other information that would be helpful for me to supply please let me know.
Thanks.

**Comment by davidscotson** [comment]
Two things you could check are:

1. Is the admin settings block actually there in the HTML? It should have an id=inst5 and class="block_settings"
2. Is there something breaking the JS on the front page? There should be a way to view JS error messages in your browser's developer tools. In Firefox it's called the "Web Console"

**Comment by cb526** [comment]
Thank you for your response and suggestions. 
The culprit was a plugin called block_my_enrolled_courses. Once I removed that from the front page the problem was resolved. :+1:
