### ISSUE TITLE
Secure layout needs updating to remove all links.

### ISSUE THREAD

**Issue by lazydaisy** [moodlerooms/moodle-theme_snap#18]
The 'a' link in the brand nav bar needs removing as there should be no links that take the user away from page. No home links, no breadcrumb, no log out in header or footer.
Clean theme's  layout/secure.php in Moodle 2.9 and 3.0 are correct if you need a model.

**Comment by davidscotson** [comment]
Hi Mary,

thanks for the bug report, I've committed a fix internally, I'll post back here once it's made its way through QA and been released.
