### ISSUE TITLE
Message from the dead

### ISSUE THREAD

**Issue by bmbrands** [moodlerooms/moodle-theme_snap#2]
In my messages tab I can see a message from a deleted user: (Brian)

![screen shot 2015-05-05 at 19 48 23](https://cloud.githubusercontent.com/assets/491790/7479133/e8477954-f35f-11e4-9459-aeb372a9d98d.png)

Clicking it brings up an error:

![screen shot 2015-05-05 at 19 50 17](https://cloud.githubusercontent.com/assets/491790/7479146/f931bdd8-f35f-11e4-83f2-75374d05207b.png)

**Comment by stuartlamour** [comment]
best bug title EVER ;)

**Comment by gthomas2** [comment]
This has been kicking around for ever - adding an internal ticket to deal with this.

**Comment by stuartlamour** [comment]
fixed in 3.0 :)
