### ISSUE TITLE
How do I put custom Links at the top of the page?

### ISSUE THREAD

**Issue by matthewbassett** [moodlerooms/moodle-theme_snap#20]
Is there a way to display custom links at the top of the page? If I enter in custom menu items in the theme settings page, the links are displayed at the bottom when using the Snap thing? Is there something I'm missing in the settings? Or is Snap not designed to be used in that way?

**Comment by stuartlamour** [comment]
Hi Matthew, that is a deliberate design feature you're right. 

We choose to keep the header focused on the primary tasks for learners and educators on mobile through to desktop without the temptation to add distractions.

I have seen snap customized to add links to the sidebar for messages, calendar etc similar to canvas and learn but no idea if this worked well for users.

![snap-side-icons](https://cloud.githubusercontent.com/assets/1636482/12169738/9c4a32c2-b532-11e5-9b44-77b5a2e9c1ae.png)

Out of interest what links did you want to add?

**Comment by matthewbassett** [comment]
Thanks for the reply!
We have a few other sites that we use at our school (school website, school
blogging platform, powerschool, Library website, etc... In the past we have
used moodle as a launching point to be able to get to any of the other
sites. We may rethink that plan, as I agree that it can be distracting from
the content. Putting the links in the footer though seems like a bit of a
waste as well, as our eyes have been trained to not read the footer of
websites, and it causes the same distracting use of space. hmm... I'll have
to keep thinking on that.

Thanks again for the detailed reply. Really do like the theme alot (:

Matt



On Thu, Jan 7, 2016 at 7:35 PM Stuart Lamour <notifications@github.com>
wrote:

> Hi Matthew, that is a deliberate design feature you're right.
>
> We choose to keep the header focused on the primary tasks for learners and
> educators on mobile through to desktop without the temptation to add
> distractions.
>
> I have seen snap customized to add links to the sidebar for messages,
> calendar etc similar to canvas and learn but no idea if this worked well
> for users.
>
> [image: snap-side-icons]
> <https://cloud.githubusercontent.com/assets/1636482/12169738/9c4a32c2-b532-11e5-9b44-77b5a2e9c1ae.png>
>
> Out of interest what links did you want to add?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moodlerooms/moodle-theme_snap/issues/20#issuecomment-169636604>
> .
>
-- 
Thanks,

Matt

**Comment by stuartlamour** [comment]
Hi Matthew,

If you have a consistent header menu across all your sites, like http://www.bbc.co.uk/ and other websites, I can totally understand why you'd want that on your Moodle instance too. 

I'd personally start by looking at nav.php in the layout file and seeing what you can do from there. Snap uses bootstrap so the http://getbootstrap.com/javascript/#dropdowns would work well and i've seen these used quite effectivly before in the Snap footer.

It's obviously technically possible to add a consistant portal style header navigation to Snap, and we would be very happy to support any plugins to help users impliment this pattern, but it's unfortunately not something at this point in time we can prioritise our core work on - apologies.
