### ISSUE TITLE
Editing options not visible

### ISSUE THREAD

**Issue by relecand** [moodlerooms/moodle-theme_snap#22]
Moodle 2.9.4
Snap 2.9

I do not see the editing options (e.g. for the forum).

![screen_shot_2016-02-04_at_10 31 26](https://cloud.githubusercontent.com/assets/5286499/12811142/d2925914-cb2a-11e5-8e3a-b889d5395db6.png)

Thank you for this theme!

**Comment by gthomas2** [comment]
Thank you for reporting this bug.
We think we know what is causing it - it seems to be when you have moodle accessed via a sub path instead of the root of the url.
E.g.

www.myfancyurl.com/mymoodle/course/view.php?id=2

as opposed to just

www.myfancyurl.com/course/view.php?id=2

**Comment by gthomas2** [comment]
OK - we've fixed this in a temporary branch:

https://github.com/gthomas2/moodle-theme_snap/tree/fix/INT-9199_course_view_javascript

Main repo will be updated after automated build checks finish and it is approved.

**Comment by relecand** [comment]
Thank you! That was fast!
