### ISSUE TITLE
Not an issue - a question....

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [moodlerooms/moodle-theme_snap#25]
Hi Stuart et al,

Sorry this is a simple (I hope) question - does the 2.9 version have dependencies on Moodle 2.9?  If so, will this be the development model going forward i.e.: there will be no updates to the 2.9 version once the 3.0 version is complete?

Thanks,
  Andrew

P.S. We are Moodlerooms users but liked Snap so much we are using it at our Uni.

**Comment by stuartlamour** [comment]
Hi Andrew,

that is a very good question - let me find out!

**Comment by gthomas2** [comment]
Hi Andrew - as far as I know, there will be no updates to the 2.9 version once we move on to the 3.0 version.

**Comment by andrewrowatt-masseyuni** [comment]
Thanks all!
