### ISSUE TITLE
Snap theme Installation error in Moodle 3.02

### ISSUE THREAD

**Issue by pranavgate** [moodlerooms/moodle-theme_snap#26]
Hi all,
I really liked snap theme but when i try to install the theme in the latest Moodle 3.02 version i get the following error .Any ideas how to remove the below error will be useful

Coding error detected, it must be fixed by a programmer: page layout file [dirroot]/theme/clean/layout/ does not contain the main content placeholder, please include "<?php echo $OUTPUT->main_content() ?>" in theme layout file. 

Thanks in Advance

**Comment by davidscotson** [comment]
The error seems to be talking about something in the Clean theme, based location given in the error message.

Does the error go away if you remove the theme/snap directory? Possibly you changed something in theme/clean at the same time as installing Snap?

**Comment by pranavgate** [comment]
Thanks for info the issue is resolved ,by changing the name of folder from moodle_theme_snap_master to only snap worked ,The theme works on moodle 3
