### ISSUE TITLE
how to move Quiz navigation block to left or right instead of bottom ?

### ISSUE THREAD

**Issue by pranavgate** [moodlerooms/moodle-theme_snap#27]
Hi ,
In snap theme the quiz navigation bar is at bottom which creates problem as we have quizzes with around 20-30 questions,we have to display all of them in one page  .
How to move Quiz navigation block to left or right instead of bottom as in normal moodle.
What to change ,i tried to make change the css with firebug but no use
This is the best moodle  theme,but i think due to quiz navigation block at bottom ,it will be not be useful for many others
Any help TO MOVE the quiz navigation block to left or right will be appreciated,

**Comment by gthomas2** [comment]
If you add the following CSS to the snap custom css setting it will put the quiz navigation at the top of the screen. There are some issues with it though - it will support up to 30 questions OK but after that point the question navigation will grow to a point where it starts overlapping the breadcrumbs / other page content.

body#page-mod-quiz-attempt #mod_quiz_navblock .qn_buttons.multipages {
    position: fixed;
    top: 2em;
    z-index: 999999;
}

body#page-mod-quiz-attempt #page-header .breadcrumb-nav {
    margin-bottom: 0;
    float: none;
    margin-top: 6em;
}
