### ISSUE TITLE
No course editing, moving activities

### ISSUE THREAD

**Issue by tokyokevin** [moodlerooms/moodle-theme_snap#28]
I cannot move things around, one of the main features of the theme. On my copy (running on Moodle 2.9.4, installed on a host with cpanel), everything is there except the ability to edit the course. No move or delete icons on the content. This has to be something to do with permissions (I am set as a manager), but thought someone might have another suggestion (ie. general theme settings). Any help appreciated. 

<img width="350" alt="course__presenting_our_world_today_2015" src="https://cloud.githubusercontent.com/assets/3771390/13200089/4b94beba-d87d-11e5-8b9a-a9a1b8452db4.png">

**Comment by gthomas2** [comment]
@tokyokevin - There was an issue preventing editing where moodle was accessed via a sub path of a url, e.g.

http://mymoodle.local would work fine

but

http://myintranet.local/moodle would break on course editing

This was fixed recently and integrated. When did you download the theme? Perhaps pulling or downloading the latest version would help?

Please let me know if you are already on the latest version and I'll investigate this further. Also, please let me know if my advice resolved the issue for you. Thanks in advance.

**Comment by tokyokevin** [comment]
Thank you, yes, the new version does seem to address this. I can move and edit now. Just a heads up, though, the placement of the buttons is a bit wonky in my version. Thanks for the quick response!
<img width="158" alt="course__test_course" src="https://cloud.githubusercontent.com/assets/3771390/13243261/750883ca-da40-11e5-9fff-714a6f64a516.png">

**Comment by gthomas2** [comment]
@tokyokevin - Does purging caches help? Have you added any custom CSS to the theme?

**Comment by tokyokevin** [comment]
Have purged caches, and no custom CSS, but no change in placement of icons
for moving, editing, more. Icons work, but do cover up descriptions of
course activities.

*************************
Kevin Ryan. Tokyo. Most places on the net I am tokyokevin.

**Comment by gthomas2** [comment]
Thanks Kevin. We have replicated your issue and are working on a fix.

**Comment by stuartlamour** [comment]
hi tokyokevin,

thanks for your help in spotting bugs.

we just updated the repository to our final 2.9 version and 3.0 is on the way in the next month.

please do continue to report anything you find and help us improve snap.

cheers
stuart lamour
