### ISSUE TITLE
enrol/accesskey:manage

### ISSUE THREAD

**Issue by bmbrands** [moodlerooms/moodle-theme_snap#3]
There is a capability check for a capability that does not exist in standard Moodle

![screen shot 2015-05-05 at 19 52 35](https://cloud.githubusercontent.com/assets/491790/7479209/5f02c080-f360-11e4-9751-36fd276e1ba3.png)

**Comment by techxplorer** [comment]
@bmbrands Many thanks for bringing this to our attention. I have developed a fix and it is currently undergoing our internal code review processes. When it passes, we will updated our GitHub repository with the latest code. Please 'watch' the repository for updates.

**Comment by jinobi** [comment]
Hi, Could you update on the status of this issue? The Course Tools and Blocks section is not getting loaded because of this. Thank you for your attention.

**Comment by davidscotson** [comment]
Hi,

the fix is made in our internal branch which should be getting opened to github in the coming week.
