### ISSUE TITLE
Sections and section content

### ISSUE THREAD

**Issue by davidgmitchell** [moodlerooms/moodle-theme_snap#30]
Hi
We have a course with 18 sections, but this causes a strange usability issue. When a user clicks one of the sections nothing changes on screen for them, because the section content is being shown below the current viewing area. This makes it look like a fault, or that it is unresponsive, when what they need to do is scroll down the page.

Intermittently this appears to scroll down the page to the top of the section's content, but this normally only happens when the page first loads - not on subsequent section changes. Ideally it would focus on the section content, whenever the user selects a section.

Thanks,
David Mitchell

**Comment by stuartlamour** [comment]
Hi David, i believe this has already been reported via customer support so hope you don't mind me closing it here as it's not a technical bug.
Cheers
Stuart

**Comment by davidgmitchell** [comment]
Hi Stuart,
Customer support didn't really offer me a solution though, except to remove some custom CSS that was increasing the font size. I have done that, but it is still an issue.
Can I just suggest this as a potential future additional to the SNAP theme and leave it here?

Thanks,
Dave

**Comment by stuartlamour** [comment]
Hi David, from the screenshot it looks like you have a lots and lots of text (really long section title in the table of contents) which just is going to take up a lot of screen real estate. I'm not sure i can offer any technical html/css or js 'solution', but personally i'd try shorter section titles?

**Comment by davidgmitchell** [comment]
Hi Stuart, we are going to reduce the number of sections and, hopefully, the length of the section titles. Seems like we're being restricted (both in title length and the number of sections) by the theme though, instead of it working for us.

Is there a way we could have an option to open the sections in a new window? (that could be turned on or off)

Thanks
Dave
