### ISSUE TITLE
"too Long file path"

### ISSUE THREAD

**Issue by AluminiumTech** [moodlerooms/moodle-theme_snap#32]
Snap cannot be extracted to a new folder due to an error about a "Too long file path"

**Comment by davidscotson** [comment]
I think this may be a Windows issue, rather than anything special about the zip file. Have you tried extracting the zip file in another location (one with a shorter path) to see if it succeeds there and then moving it?

**Comment by davidscotson** [comment]
Could you provide the full error message, and the context in which it is being given e.g. the app that's doing the extraction. Thanks, it will help us look into this issue
