### ISSUE TITLE
Resource/Activity action button placement issue

### ISSUE THREAD

**Issue by upats** [moodlerooms/moodle-theme_snap#33]
The **Move, Edit, and More** buttons for resources/activities are placed weird. See picture below. They should probably not cover up the animated icons or text of the resource. Also, when clicking the **More** button for a resource on the left of the course content area, the z-index appears to be messed up. The menu gets hidden behind the wrapper div. The image below shows both of these issues (notice the menu box cuts off on the left... sorry--kind of hard to see it):

![snip_20160602104254](https://cloud.githubusercontent.com/assets/7084108/15754907/405782b2-28af-11e6-8916-2585f0537f28.png)

I'm testing this in Moodle 3.0

**Comment by stuartlamour** [comment]
hi upats,

thanks for reporting this.

we just updated the repository to our final 2.9 release, 3.0 release is coming in the next month with some new features including course favoriting which you can see in this video 

https://www.youtube.com/watch?v=yPfuRSkxEfo&list=PLvWuynT7Aq_0uNohSwRucH7R3m_RSSbNI&index=1&ab_channel=StuartLamour

marking this as closed, but please let do continue to let us know of any issues you find.

Cheers
Stuart
