### ISSUE TITLE
Improvement: Course menu

### ISSUE THREAD

**Issue by upats** [moodlerooms/moodle-theme_snap#34]
Stuart, thanks for the reply to my other issue. Looking forward to the 3.0 version of Snap.

The [video you linked to](https://www.youtube.com/watch?v=yPfuRSkxEfo&index=1&list=PLvWuynT7Aq_0uNohSwRucH7R3m_RSSbNI) made me think of another idea we have for the theme. in fact, this is a deficiency throughout the entirety of Moodle, but one we've fixed with a [customized block](https://moodle.org/plugins/view.php?plugin=block_custom_course_menu&moodle_version=21). This block lets you sort, hide, or collapse courses based on the category they are in allowing you to be free of the problem you addressed in the video: the potential for a huge number of courses that you can't sort through easily.

Your favorites feature for 3.0 looks awesome! We have the same feature in our block as well as a 'last X courses viewed' "category." 

To me, your theme is nearly perfect. The biggest downside to it is this course navigation menu. Since the theme takes emphasis away from the usage of blocks, it basically forces you to into using the built in drop-down course menu to navigate. Because of that, I think the course menu needs to be top-notch or it will be a barrier to many people who would otherwise switch to this beautiful theme.

The only way we can get by using the theme for the time being is by allowing instructors to enable it on a course-by-course basis. I'm looking forward to the evolution of this!

**Comment by stuartlamour** [comment]
hi upats

we are always looking for input into the theme and if you'd be happy to talk email me at slamour@moodlerooms.com 

cheers
stuart
