### ISSUE TITLE
Auto-jump to current topic/week

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [moodlerooms/moodle-theme_snap#35]
Hi,

Is it possible to automatically jump to the current topic/week when opening a site with this theme?

Thanks,
   Andrew

**Comment by stuartlamour** [comment]
Hi andrew,

it's on the roadmap but not in the current version i'm afraid.

Cheers
Stuart

**Comment by stuartlamour** [comment]
Hi Andrew, 

this should be in the 3.0 mp1 release in August.

Cheers
Stuart

**Comment by andrewrowatt-masseyuni** [comment]
Thanks Stuart!  Keep up the good work.

Cheers,
   Andrew

--

**Comment by stuartlamour** [comment]
apologies andrew, 

this was considered too much of a change in functionality to release in a maintenance pack so will be part of the next upgrade - snap 3.1 for december 2016.

**Comment by Kylie-Marie** [comment]
Has there been any update or news on the release of the Major Upgrade SNAP 3.1 (although we like to the original PD, DOC etc icons ;-) )

**Comment by davidscotson** [comment]
Hi Kylie-Marie,

we run a version behind the main Moodle releases (for stability reasons) so our 3.1 release is this month, to be ready for the new year. The official release will be shortly after that, probably early next year, but the code currently in the master branch is basically what will be released as the 3.1 branch and has this change included already if you wish to test it out.

**Comment by Kylie-Marie** [comment]
Wonderful :) I'll pass that info on -  I believe we did run a beta version at one stage but some bugs occurred. I'm simply a user/designer of our RTO''s LMS and we have an external provider for the behind the scene's details, codign etc. I have some understanding just not the practical skill set to do so, so we removed the beta and went back to the original snap package.
 
Another question too now sorry - and correct me if this is in the wrong location, or a solution has been provided - the assessment grading page doe snot display the students name, as it would in a basic Moodle platofrm. To note: we've added a pdf plugin and ghostwriting software to enable marking in the LMS.
Is it the theme affecting this display of the student name?

**Comment by davidscotson** [comment]
Hi Kylie-Marie,

I'm not aware of any bug like that. Do you mean on this page?

joule2.dev/mod/assign/view.php?id=6939&action=grader

I can see the user image and name at the top in Snap and in Clean, on Moodle 3.1.

An example url and a screenshot of what you are seeing (or not seeing) would help us to track it down for you.

**Comment by Kylie-Marie** [comment]
[Assessment Grading page not right.pdf](https://github.com/moodlerooms/moodle-theme_snap/files/658560/Assessment.Grading.page.not.right.pdf)

Sorry David I couldn't access your URL but I have a screenshot of 3.1 and our SNAP that I sent to our support provider for them to figure out.

**Comment by davidscotson** [comment]
I'm not sure what the problem might be in that screenshot, it seems as though the student's submission isn't displaying correctly. I've not seen that in our local version of Snap, but I'll look further into it to see if I can figure it out.

**Comment by Kylie-Marie** [comment]
It has since rectified itself it seems, we have just installed the most recent patch :)
