### ISSUE TITLE
Course admin block not available for students

### ISSUE THREAD

**Issue by lesleyjane** [moodlerooms/moodle-theme_snap#36]
Hi 
I have found that the Admin button is not available for students in SNAP, although if you switch to the student role, it does appear to be there.

This means that students don't have the option to print a book or a chapter. They also can't see their gradebook in the Course Admin block.

This is an issue for me and my team as we want students to be able to print a book so that they can do some work offline.

Do you have any suggestions on how to make the Admin button available for students?

Many thanks
Lesley

**Comment by stuartlamour** [comment]
Hi Lesley,

If you are using the latest version of Snap you should find the link as so : 

<img width="347" alt="screen shot 2016-07-19 at 17 07 53" src="https://cloud.githubusercontent.com/assets/1636482/16957284/b02a1796-4dd3-11e6-9781-358420f484a6.png">

**Comment by lesleyjane** [comment]
Thanks for replying so quickly. I probably don't have the latest version - but will get that organised.

Many thanks.

**Comment by stuartlamour** [comment]
As for feedback/grades - Learners can access their grades/feedback in lots of ways in Snap.

In the personal menu for each course if the user has been given feedback a link to view their feedback for that course shows.

In the personal menu feedback column users can view the page showing all their feedback in moodle.

In any course users can access the course tools and view their feedback.

Let me know if for any reason this isn't working.

Cheers
Stuart

**Comment by andrewrowatt-masseyuni** [comment]
Sorry to hijack this thread but on a related matter how can students access the "unsubscribe from forum" options that appear in the admin block?

P.S. We are using Snap 2.8
