### ISSUE TITLE
Moving sections

### ISSUE THREAD

**Issue by lesleyjane** [moodlerooms/moodle-theme_snap#38]
We've upgraded SNAP and it looks good. But I can't see how to change the order of sections. It wasn't particularly easy to do in the earlier version of SNAP, but now we're having to change to Clean theme to add in new sections or change the order of sections. Am I missing a trick?

Another quibble is the numbering of sections in the contents. It looks like we will need to turn this off in the code.

**Comment by stuartlamour** [comment]
hi @lesleyjane,

this might help https://www.youtube.com/watch?v=IPwzzHjikIc&index=4&list=PLvWuynT7Aq_0uNohSwRucH7R3m_RSSbNI&ab_channel=StuartLamour

**Comment by lesleyjane** [comment]
Aha! Thanks, excellent - much better. 
Useful set of videos
