### ISSUE TITLE
String concatenation in the lang pack file

### ISSUE THREAD

**Issue by mudrd8mz** [moodlerooms/moodle-theme_snap#39]
Unfortunatelly, there is a limitation in our tools processing the plugins language files that they have to parse the lang files instead of evaluating them as PHP files. For that reason, things like string concatenation in `$string['poweredbyrunby']` will not work and will prevent the plugin to be registered with AMOS at the moment.

You may wish to get rid of this operators and release a new version to get it registered with AMOS. Please see https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings for details.

**Comment by gthomas2** [comment]
Thanks for making us aware of that David ;-)

**Comment by germanvaleroelizondo** [comment]
This issue has not been solved :(

As a result, AMOS only hosts the English language strings for the Moodle 2.7 and 2.8 versions of this plugin. More modern versions of this plugin do not have their language strings available for translation, which is a real pity, being such a nice and likeable theme.

Please read the developer's documentation at https://docs.moodle.org/dev/Translating_plugins#If_translations_are_available_in_AMOS_for_some_Moodle_branches_but_not_available_for_other_branches

**Comment by stuartlamour** [comment]
Hi @germanvaleroelizondo - just pushed a fix which should be available as soon as it's gone through code review, ci and qa process.
Thanks for the reminder on this.
Stuart

**Comment by germanvaleroelizondo** [comment]
Thanks Stuart,

I will be looking forward to translating (into Mexican Spanish) the new English language strings for the versions for the more recent Moodle branches.

Thanks again,
German

**Comment by mudrd8mz** [comment]
I really need to find some time and improve the AMOS parser to support this case as well.

**Comment by germanvaleroelizondo** [comment]
I am afraid that even today, AMOS only has English language strings for Moodle 2.7 and 2.8 versions of this plugin :(

With Moodle 3.3 around the corner, it is a pity that this nice theme does not support languages other than English for the more recent Moodle branches.

**Comment by davidscotson** [comment]
Hi, we thought we'd fixed this, but it turns out we didn't. Thanks for reminding us, we'll get this sorted on the master branch soon.

**Comment by davidscotson** [comment]
I've uploaded a new 3.1 version to plugin db, and committed the same change to our internal 3.2 branch. I got a message about AMOS detecting 236 strings so I think it should work now, but if anyone can confirm that it's suitable for translators now, that would be great.

**Comment by mudrd8mz** [comment]
Thanks David. I can confirm the Snap strings are now available in AMOS for translation.

**Comment by davidscotson** [comment]
Excellent! Thanks for confirming that David.

**Comment by germanvaleroelizondo** [comment]
Unfortunately, AMOS has strings **only** for Moodle branches 3.1, 2.8 and 2.7 :(
![snap language strings branches available in amos](https://cloud.githubusercontent.com/assets/2671923/25670544/a8c7ee86-2ff2-11e7-8050-e15586fa6eb1.png)


It seems that there are still some language string issues remaining. Otherwise, this is a really nice plugin and Moodle users from non-English countries would really like to have this plugin translated in all modern Moodle branches.

**Comment by mudrd8mz** [comment]
I don't think it is a problem. The translation of the 3.1 version (which is the latest from https://moodle.org/plugins/pluginversions.php?plugin=theme_snap) will be used in all later Moodle versions implicitly.
