### ISSUE TITLE
Errors installing Snap theme on Moodle 3.1.1+ (Build: 20160817)

### ISSUE THREAD

**Issue by appkabob** [moodlerooms/moodle-theme_snap#40]
Hello,

We are having some trouble installing the theme. We were running Moodle 3.0 and got an error that our installation was too old to install Snap theme. So today we upgraded to Moodle 3.1.1+ (Build: 20160817) and I tried installing Snap again.

First, by going to Site Administration > Plugins > Install Plugins > "Install plugins from the Moodle plugins directory" plugin and attempting to do an automatic "Install Now" of version 3.0.4 (Build: 20160509) (2016042904). This results in the following error:

`tool_installaddon/installing_non_installable_component`

The "More information" link provided goes to a dead end: https://docs.moodle.org/31/en/error/tool_installaddon/installing_non_installable_component

The second method we tried was to download Snap version 3.0.4 (Build: 20160509) (2016042904) as a .zip file and upload it under Site Administration > Plugins > Install Plugin. This results in the following error:

```
Validating theme_snap ... Error
  [Error] Extracted file not found [{"file":"snap\/javascript\/blanket\/"}] 
Installation aborted due to validation failure
```

So lastly, we tried uploading the snap folder via FTP to our Moodle's theme folder, updating the database under Site Administration > Notifications, and then choosing it as our active theme under Site Administration > Appearance > Themes > Theme Selector.

This caused the site not to load. Every page appeared as a blank white screen. When I checked the page source, it looked like the page simply stopped loading after the html header.

So I deleted the snap folder out of our theme folder, which allowed site pages to load again and I was able to revert to the theme we were using previously.

We would really like to use this theme. Any suggestions for what might be going wrong and what else we could try?

Thanks!

**Comment by ndenmeade** [comment]
I am also very keen to see the next release suitable for Moodle 3.11.

**Comment by gthomas2** [comment]
@appkabob - The last method you tried (uploading via FTP) is pretty much how I install Snap and sadly I can't replicate your problem.
Can you please let us know the following:

a) Your operating system + version
b) Your  web server + version
c) Your database server + version
d) The contents of your php log file following a post Snap theme white screen of death (you can just give us the relevant entries, not the whole log).

Thanks in advance

Guy

**Comment by gthomas2** [comment]
@ndenmeade - sorry, we don't have a 3.11 version available yet. I'll see what we can do to address this for you.

**Comment by lcolom** [comment]
Hi @gthomas2,

I got same bug as @appkabob using snap theme, every page appeared as a blank white screen. 

Since I had only one administrator account and as I already had selected the theme snap, it was no longer possible to change to another theme because any pages were not loaded after login. 
Without login, then pages were loaded using snap theme.

So I tested using a new moodle installation without loaded courses, and in this instance 
-snap theme loaded pages properly after login
-immediately I activated a course, then the pages (all: my, course, profile...) were not loaded using snap theme and showed a white screen.

I attempt to answer your questions, perhaps there is some mistake because I'm not a technician

operating system Linux, I don't know version
web server Apache, I don't know version
database mysql version 5.5.50
php executed as FasctCGI, php version 5.4.45

I don't know how to find php log.

Apologies for my poor English. Best regards.


Lluis

**Comment by gthomas2** [comment]
@lcolom - your English is great, no need to apologise! Thank you for providing this extra information. Hopefully it will help us to replicate it and fix it soon.

**Comment by appkabob** [comment]
Hi @gthomas2,

Here is the info you requested:

Linux Kernel 3.12.50-39.ELK6.x86_64
Apache 2.2.31
MySQL 5.5.42-37.1-log
PHP 5.4.43

To try to get you the error log, I just now downloaded Snap 3.0.4 (Build: 20160509) (2016042905) from the [Moodle plugins directory](https://moodle.org/plugins/pluginversions.php?plugin=theme_snap) and uploaded it to the theme folder via FTP.

As soon as I activated it I got the white screen again, but that doesn't seem to produce a PHP error - or at least my php error log doesn't seem to have any recent errors for the Moodle site. The only error on the log is this, which I don't think is relevant:

`[23-Aug-2016 10:52:03 America/Denver] Resetting core_component cache after core upgrade to version 2016052301.07`

Which would have been from when I upgraded to Moodle 3.1 a little over a week ago.

In case it's useful, when I get the white screen and then view page source, the last two lines of HTML that render in my browser are

```
<header id='mr-nav' class='clearfix moodle-has-zindex'>
<div class="pull-right">
```

Also - I didn't discover this until now, but @lcolom made me think to try it - after installing Snap, when I visit the site without being logged in (I used a different browser), it loads just fine. Also being logged in as a guest works fine. But as soon as I log in to my admin account, I get the white screen. I did not try removing courses as @lcolom did, but if it would be useful for me to test that as well, I can.

Thanks for looking into this!

**Comment by mohankumargupta** [comment]
After installing snap theme, site appears "broken" (ie. it gives the impression that that CSS styles are not applied).  I have tested this with Moodle 3.1.1+ Windows installer on my PC, unzipping snap and putting it in theme folder. This also happened to me on my shared hosting site, but what fixed it on that site  was disabling slash arguments Administration > Site administration > Server > HTTP.

**Comment by Foresight16** [comment]
I'm also having the same problem on 3.1.1. Wouldn't disabling slash arguments stop any of my SCORM files  from working? I have a lot of them as is critical to my courses. Could you tell me more about using Bitnami? Bit new to all this, had a look on the site but can't see how using this service would fix this specific problem. Thanks

**Comment by davidscotson** [comment]
I'm closing this issue as at least the initial report about "  [Error] Extracted file not found [{"file":"snap\/javascript\/blanket\/"}] " was fixed.

If anyone is still having installation issues, could you open a seperate issue, and provide the standard version info as provided above, thanks
