### ISSUE TITLE
“All courses” not available on personal menu

### ISSUE THREAD

**Issue by daveyboond** [moodlerooms/moodle-theme_snap#46]
The “browse all courses” button on the personal menu only appears to admins, not to students, and there seems to be no way to enable or add it. This is a problem when a site uses self-enrolment on most courses.

**Comment by stuartlamour** [comment]
Hi @daveyboond - the browse all courses is shown based on $CFG->navshowallcourses. You can set this from Admin settings/apperence/navigation
<img width="820" alt="screen shot 2016-11-17 at 16 57 50" src="https://cloud.githubusercontent.com/assets/1636482/20398913/07ac782a-ace7-11e6-9c39-29a08d189c2e.png">

**Comment by daveyboond** [comment]
Aha, thank you Stuart!
