### ISSUE TITLE
Few notices on the course view page when the resource doesn't have an icon

### ISSUE THREAD

**Issue by mouneyrac** [moodlerooms/moodle-theme_snap#5]
On /course/view.php?id=1698#section-1 in the debug errors section:

```
Notice: Undefined offset: 1 in /var/www/html/assessment_manager/moodle/theme/snap/renderers/course_renderer.php on line 296

Notice: Undefined offset: 1 in /var/www/html/assessment_manager/moodle/theme/snap/renderers/course_renderer.php on line 324
```

It is due to the resource not been properly upgraded during 1.9 to 2.X upgrade. To fix it before the lines you can add:

```
if (empty($matches['1'])) {
    return ['',''];
}
```

and

```
if (empty($matches['1'])) {
    return false;
}
```

I guess you may close this issue as it's likely to going to happen to very few people and most likely only on sites with not ported resource or with resource missing the type file icon (which in this case is a coding problem on the resource). But I think it was worth to mention for people having similar issue.

**Comment by mrjason** [comment]
Seems like an obscure issue going to close this as something we don't plan to work on.

**Comment by mouneyrac** [comment]
Yes it is probably almost not going to happen and I provided a workaround :) I close it for you.
