### ISSUE TITLE
Icons from 3.0 and using them with the update

### ISSUE THREAD

**Issue by Kylie-Marie** [moodlerooms/moodle-theme_snap#50]
Hi guys

We really loved the old icons and blocks in SNAP 3.0, however to get the progress bar working correctly we have gone with 3.1 - the progress bar looks great but the icons have been 'updated'.
Is there a way to have the best of both worlds? Our support developers have been able to brign across the smaller icons but the larger elements and blocks/icons have not worked so well.

I hope this makes some sense and some guidance or help is possible :) 

![icons 1](https://cloud.githubusercontent.com/assets/24399399/21520999/d87356fa-cd48-11e6-84eb-ea96aaf5bd00.png)
![icons 2](https://cloud.githubusercontent.com/assets/24399399/21521004/d9dcae7e-cd48-11e6-8fad-8f0ce64836ca.png)
![small icons](https://cloud.githubusercontent.com/assets/24399399/21521000/d8b2fec2-cd48-11e6-8385-8086d442fd0f.png)
![url icon](https://cloud.githubusercontent.com/assets/24399399/21521001/d8f22642-cd48-11e6-9047-2740e5cea122.jpg)
![blocks](https://cloud.githubusercontent.com/assets/24399399/21521002/d92f23ee-cd48-11e6-820a-7d50ae23df5a.jpg)

**Comment by stuartlamour** [comment]
Hi @Kylie-Marie 

within a theme icons for mods are in the pix_plugins/mod folder, and icons for resources are in pix_core/f folder.
