### ISSUE TITLE
Cannot move activities into to Main Menu block on front page

### ISSUE THREAD

**Issue by daveyboond** [moodlerooms/moodle-theme_snap#52]
Hi,

In other themes (e.g. Clean), it is possible to move activities from the main topic section on the Front Page into the Main Menu block, and vice versa. Under Snap, you can only move from Main Menu to the topic section, not the other way. To do so, I have to swap to a different theme.

Steps to reproduce:
1. Go to front page of Moodle and turn editing on
2. Add a "Main Menu" block at the bottom
3. Add a new label to the Main Menu block
4. Click the 'Move' button for the new label and drop it into the main topic section
5. Click the 'Move' button for the label in its new position - there is no option to drop it back in the Main Menu block

Steve

**Comment by stuartlamour** [comment]
Hi Steve,

interesting one...  Snap isn't really designed for you to have to use moodle blocks for content on the front page.

If you are trying to layout content in a number of columns i'd highly recommend this plugin https://www.youtube.com/watch?v=obVRi68lbvs 

Cheers
Stuart
