### ISSUE TITLE
Site News on Front Page does not show attachments

### ISSUE THREAD

**Issue by daveyboond** [moodlerooms/moodle-theme_snap#53]
Site News (when displayed as News Items in Front Page Settings) does not display any attachments made to posts. These are only visible when you click “More news” button.

So, Site News when you first view Front Page looks like this:
![image](https://cloud.githubusercontent.com/assets/1135243/21853609/c05aa1c8-d80f-11e6-84c9-9e16ccf2db85.png)

Then when you click on the 2nd news story - message shows, but no attachment:
![image](https://cloud.githubusercontent.com/assets/1135243/21853625/cb99e3be-d80f-11e6-8421-90e29225671a.png)

Viewed via 'More news' button, the attachment can be seen:
![image](https://cloud.githubusercontent.com/assets/1135243/21853659/e4081790-d80f-11e6-954c-b0b310551566.png)

Could Snap be made to show a link to the attachments?

Thanks

Steve

**Comment by stuartlamour** [comment]
Hi @daveyboond - have you tried adding whatever files you are attaching within the html editor? That should make for a much better user experience generally.

**Comment by daveyboond** [comment]
Well we did decide on that as a workaround. I agree, it does look better inline.

I still think this behaviour would trip users up, but I can see it's not a priority.

Cheers

Steve

**Comment by stuartlamour** [comment]
Ideally we should relabel the post attachments box as post image in snap, but not too sure how to do that at this point so apologies.
