### ISSUE TITLE
Jump back to last viewed week/topic after adding a resource/activity

### ISSUE THREAD

**Issue by upats** [moodlerooms/moodle-theme_snap#54]
Current functionality works as such: When adding an activity or resource to a week, after you click "Save and return to course" you get sent back to the first week/topic section in the course.

The expected behavior would be to get sent back to the week you just added content to.

This can be an encumbrance to people who are building a new course and have to keep jumping between sections after they have added new content.

**Comment by stuartlamour** [comment]
Hi @upats 

this workflow isn't one i'm able to replicate. 

Creating a resource always contains section=4 in the url.

Savinging always returns you to that section.

Can you provide any more details on how this isn't working on your specific instance?

**Comment by upats** [comment]
Sorry Stuart--user error (not letting the page finish loading). I'll close this.
