### ISSUE TITLE
profile menu

### ISSUE THREAD

**Issue by martinvivek** [moodlerooms/moodle-theme_snap#56]
profile menu and my courses are working for my courses only. so users cannot logout.

**Comment by stuartlamour** [comment]
Hi Martin, could you add a screenshot to provide a little more detail? Thanks.

**Comment by martinvivek** [comment]
![image](https://cloud.githubusercontent.com/assets/7712010/23306113/f2370e54-fac7-11e6-8aa5-7fbf09caea0e.png)
![image](https://cloud.githubusercontent.com/assets/7712010/23306188/57d64bbc-fac8-11e6-8a3e-90af9100c596.png)

Theses menus not showing and the personal menu is that i thought but what it does i dont know

**Comment by stuartlamour** [comment]
Hi Martin,

we don't recommend you use these custom menu items with Snap, however they are output in the footer.

**Comment by martinvivek** [comment]
Ok thank you for prompt response. its a basic doubt in snap theme how user can change the password, the menu should appear in the user menu or the the preference link (/user/preferences.php) but it is not there

![image](https://cloud.githubusercontent.com/assets/7712010/23306995/dfacf57e-facb-11e6-9e57-3849cc9c88fb.png)

**Comment by stuartlamour** [comment]
Hi Martin,

open the personal menu and click on your name to see your profile page.

From there you can edit your profile and change the password, or go to the preferences page in your screenshot.
