### ISSUE TITLE
forum alignment

### ISSUE THREAD

**Issue by martinvivek** [moodlerooms/moodle-theme_snap#58]
the alignment is not good in forum enclosed screen shot and if it has a border for a post it would be good. 
![image](https://cloud.githubusercontent.com/assets/7712010/22626115/3992acaa-ebcc-11e6-80b5-63237ddb7461.png)

**Comment by stuartlamour** [comment]
hi @martinvivek 

snap 3.2 inherits from the boost theme so any alignment issues should be reported to core.
