### ISSUE TITLE
"Save and Return to Course" button missing from single page course

### ISSUE THREAD

**Issue by alecmyers** [moodlerooms/moodle-theme_snap#59]
Can't create a single page course, because the "Save and return to course" button is absent - cancel button is the only option. See image below.

![screen shot 2017-03-15 at 12 25 26 pm](https://cloud.githubusercontent.com/assets/1629648/23959095/8f29b624-097a-11e7-9de3-3898ec98dc08.png)

By contrast creating pages in multi section courses the "Save and return to course" button exists and works great:
![screen shot 2017-03-15 at 12 25 02 pm](https://cloud.githubusercontent.com/assets/1629648/23959101/939be038-097a-11e7-9a1d-c0eaeb7fdc77.png)

**Comment by stuartlamour** [comment]
Hi @alecmyers,

can you let us know what the Type of activity is set to?

**Comment by alecmyers** [comment]
It's set to 'Page'.

BTW this is with moodle 3.2 - I think you declared Snap incompatible with this, but to be honest it installed fine and I've been using it for months with no problems.

**Comment by stuartlamour** [comment]
hi @alecmyers,

yes, its probably a good idea to use the version of snap for your moodle version.

I'm not sure we can help with version incompatibilities - apologies.
