### ISSUE TITLE
No messages are retrieved in the nav menu (with postgres)

### ISSUE THREAD

**Issue by mouneyrac** [moodlerooms/moodle-theme_snap#6]
I wanted to check the performance of the different rest.php actions, especially the grading one (get_courseinfo, get_deadlines, get_grading, get_messages) and I noticed the action get_messages produces a sql error (postgres doesn't like 1/0 as 'unread'):

[Fri May 08 02:46:56.669094 2015] [:error] [pid 12185] [client 115.166.18.70:62345] Testing SNAP REST CALL (get_deadlines), referer: http://...
[Fri May 08 02:46:56.701094 2015] [:error] [pid 12185] [client 115.166.18.70:62345] Execution time for SNAP REST CALL (get_deadlines): 0, referer: http://...

[Fri May 08 02:46:56.712540 2015] [:error] [pid 10325] [client 115.166.18.70:62501] Testing SNAP REST CALL (get_grading), referer: http://...
[Fri May 08 02:47:03.159186 2015] [:error] [pid 10325] [client 115.166.18.70:62501] Execution time for SNAP REST CALL (get_grading): 7, referer: http://...

[Fri May 08 02:47:03.170937 2015] [:error] [pid 10891] [client 115.166.18.70:62521] Testing SNAP REST CALL (get_messages), referer: http://...
[Fri May 08 02:47:03.173894 2015] [:error] [pid 10891] [client 115.166.18.70:62521] Default exception handler: Error reading from database Debug: ERROR:  syntax error at or near "'unread'"\nLINE 3: ... AS fromuserimagealt,u.email AS fromuseremail, 1 as 'unread'\n                                                               ^\n\n        (\n                SELECT m.id, m.useridfrom, m.useridto, m.subject, m.fullmessage, m.fullmessageformat, m.fullmessagehtml, m.smallmessage, m.timecreated, m.notification, m.contexturl, m.contexturlname, u.id AS useridfrom,u.picture AS fromuserpicture,u.firstname AS fromuserfirstname,u.lastname AS fromuserlastname,u.firstnamephonetic AS fromuserfirstnamephonetic,u.lastnamephonetic AS fromuserlastnamephonetic,u.middlename AS fromusermiddlename,u.alternatename AS fromuseralternatename,u.imagealt AS fromuserimagealt,u.email AS fromuseremail, 1 as 'unread'\n                  FROM mdl_message m\n            INNER JOIN mdl_user u ON u.id = m.useridfrom\n                 WHERE m.useridto = $1\n                       AND contexturl IS NULL\n        ) UNION ALL (\n                SELECT m.id, m.useridfrom, m.useridto, m.subject, m.fullmessage, m.fullmessageformat, m.fullmessagehtml, m.smallmessage, m.timecreated, m.notification, m.contexturl, m.contexturlname, u.id AS useridfrom,u.picture AS fromuserpicture,u.firstname AS fromuserfirstname,u.lastname AS fromuserlastname,u.firstnamephonetic AS fromuserfirstnamephonetic,u.lastnamephonetic AS fromuserlastnamephonetic,u.middlename AS fromusermiddlename,u.alternatename AS fromuseralternatename,u.imagealt AS fromuserimagealt,u.email AS fromuseremail, 0 as 'unread'\n                  FROM mdl_message_read m\n            INNER JOIN mdl_user u ON u.id = m.useridfrom\n                 WHERE m.useridto = $2\n                       AND contexturl IS NULL\n        )\n          ORDER BY timecreated DESC\n         LIMIT 5 OFFSET 0\n[array (\n  0 => '2',\n  1 => '2',\n)]\nError code: dmlreadexception\n\* line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown\n\* line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()\n\* line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()\n\* line 273 of /theme/snap/classes/local.php: call to pgsql_native_moodle_database->get_records_sql()\n\* line 294 of /theme/snap/classes/local.php: call to theme_snap\local::get_user_messages()\n\* line 67 of /theme/snap/classes/controller/snap_personal_menu_controller.php: call to theme_snap\local::messages()\n\* line ? of unknownfile: call to theme_snap\controller\snap_personal_menu_controller->get_messages_action()\n\* line 90 of /theme/snap/classes/controller/kernel.php: call to call_user_func()\n\* line 53 of /theme/snap/classes/controller/kernel.php: call to theme_snap\controller\kernel->execute_callback()\n\* line 73 of /theme/snap/rest.php: call to theme_snap\controller\kernel->handle()\n, referer: http://...

[Fri May 08 02:47:03.188566 2015] [:error] [pid 11710] [client 115.166.18.70:62520] Testing SNAP REST CALL (get_courseinfo), referer: http://...
[Fri May 08 02:47:04.163681 2015] [:error] [pid 11710] [client 115.166.18.70:62520] Execution time for SNAP REST CALL (get_courseinfo): 8, referer: http://...

PS: this nav menu is a very clever solution to display the grading to do as the user only trigger it time to time. Well done.

**Comment by gthomas2** [comment]
Hmm, I don't get this error with my postgres install - (PostgreSQL) 9.3.6

@mouneyrac - please could you try it with the SQL changed to 

        -- Snap sql
        (
                SELECT $select, '1' AS unread
                  FROM {message} m
            INNER JOIN {user} u ON u.id = m.useridfrom
                 WHERE m.useridto = ?
                       AND contexturl IS NULL
        ) UNION ALL (
                SELECT $select, '0' AS unread
                  FROM {message_read} m
            INNER JOIN {user} u ON u.id = m.useridfrom
                 WHERE m.useridto = ?
                       AND contexturl IS NULL
        )
          ORDER BY timecreated DESC
