### ISSUE TITLE
'Browse all courses' function for Teacher role

### ISSUE THREAD

**Issue by Kylie-Marie** [moodlerooms/moodle-theme_snap#60]
Our Site Admin have this option on their Dashboard, however we would like our Teachers who have multiple cohorts under one program, to also have this.

I have explored and compared the roles of each (Site Admin and Teacher) but no luck. We do not want to give them Site Admin ability, just this function in particular. Am I missing the obvious?

![browse all issue](https://cloud.githubusercontent.com/assets/24399399/24175613/0d2b8324-0ee7-11e7-90b2-9370787327e1.JPG)

**Comment by stuartlamour** [comment]
Hi Kylie-Marie,

the browse all courses is shown based on $CFG->navshowallcourses. You can set this from Admin settings/appearance/navigation.

<img width="820" alt="07ac782a-ace7-11e6-9c39-29a08d189c2e" src="https://cloud.githubusercontent.com/assets/1636482/24193087/f12ba4cc-0ee8-11e7-8a85-7cb3c821af51.png">

I've never personally tried to set this permission for specific roles/users in moodle but am sure is you ask on the moodle forums folks will be able to tell you if its possible and how to do it.

Hope this helps
Cheers
Stuart

**Comment by Kylie-Marie** [comment]
PERFECT!

I cannot believe it! So simple!
