### ISSUE TITLE
Snap incompatible with Moodle 3.2?

### ISSUE THREAD

**Issue by bollycanuk** [moodlerooms/moodle-theme_snap#61]
Just tried Snap with Moodle 3.2 and it seems broken. I really like the clean look and simple interface shown on the Snap theme page here: [(https://en-us.help.blackboard.com/Moodlerooms/Administrator/020_Manage_a_Site/090_Course_and_Site_Design/Themes/020_Snap)]
- Clicking on the gear icon on the upper right does nothing. No browser activity, nothing.
- Did a clean install of Moodle 3.2.2 and added Snap theme (theme_snap_moodle31_2016121304.zip) via plugin install. Used all default settings for the theme. Same result - clicking gear icon, My Courses or my user icon does nothing .

Am I missing something or is it not compatible with 3.2? If it isn't, there should be a clear indication on the Moodle plugin page for the Snap theme that it is NOT compatible..

Cheers,
Derek

**Comment by davidscotson** [comment]
Hi Derek,

you'll need to use the version in the master branch, the 3.1 version of Snap has issues with Moodle 3.2, the work in progress is pushed out onto the master branch, but the final release supporting 3.2 won't be available till the summer (as that's when we roll out that version internally).

Good point about making this clearer, I'll look into what we can do to mark it as not compatible with 3.2.

**Comment by bollycanuk** [comment]
Thanks for the quick response! I'll give the work in progress a try from Github then.

Thanks
Derek

**Comment by stuartlamour** [comment]
Derek - i only updated to 3.2 a week or so ago, i'm fixing things pretty much every day, so might be prudent to wait a while....

**Comment by bollycanuk** [comment]
Ok thanks

Derek

**Comment by pramithkm** [comment]
Hi,

Interested in this issue as I am expecting to see a 3.2 Stable branch.
I have plans to upgrade from Moodle 3.0 to 3.2, before 3.0 runs out of support.

Cheers,
Pramith.

**Comment by mkeenan750** [comment]
Hi i have 3.2.1 version of moodle (only available via my host) and I realise that this current version isnt stable yet on 3.2, just wanted to let you know of a small bug I have seen in current version of snap, the change user menu, switch from admin student is not available, when you switch back to boost its there, thought I should report it

**Comment by davidscotson** [comment]
Hi, @mkeenan750,

we're aware of the switch role issue and it should be fixed on the master branch,

thanks for reporting the issue

**Comment by stuartlamour** [comment]
hi @bollycanuk,

closing this issue until the 3.2 release of snap is available.

Cheers
Stuart
