### ISSUE TITLE
Show max size and no of filesfor forum/assignment upload 

### ISSUE THREAD

**Issue by lesleyjane** [moodlerooms/moodle-theme_snap#68]
In SNAP at the moment you have to attempt to upload a file to see whether it exceeds the max size of the attachment set for the forum/assignment activity. 

When students are presenting photos and drawings as part of their assignment and forum work, they have to learn to manage the size of their digital files, so it is helpful for them to know the maximum file-size before they complete their assignment. 

Other themes include this information, and though it may not be included in order to give a streamlined, clean look, it would be valuable to have it as an option in SNAP settings.

**Comment by stuartlamour** [comment]
Hi @lesleyjane, 
it is just hidden with css so you can set .fp-restrictions to display: block and it will show.
Cheers
Stuart
