### ISSUE TITLE
Cannot Add block in course page

### ISSUE THREAD

**Issue by ornelasthiago** [moodlerooms/moodle-theme_snap#72]
click: edit blocks 

Select in menu add block : html block. 

The page refresh but dont show the html block.  This is for all the blocks i tryed to add in the course.

I tryed to add a block in my personal profile and in this page its possible add it.  but not in the course page. 

Any fix? Ty

**Comment by ornelasthiago** [comment]
Also , no its possible modify the config of the block. refresh to course topics page.  All of it in course tools link.

**Comment by davidscotson** [comment]
Hi,

could you give us some more details on your setup? I can't recreate this issue locally.

Your browser version, Moodle version and Snap version would be a good start.

I can add blocks, delete blocks, configure blocks etc. all on the course tools page of a course.

**Comment by ornelasthiago** [comment]
hey! ty for reply!  Well,  there are : Ópera Beta browser 46.0 / Moodle 3.1.6/Firefox 43.0.1 .

 The page refresh and then auto close the edit mode, showing only the blocks in the normal visual mode, when i try to add or delete any block in course tools section.  Also i can't edit the blocks config in this area.

**Comment by ornelasthiago** [comment]
Ah : Snap Version : 2016121304

**Comment by ornelasthiago** [comment]
Hi Again! Any progress? 

Regards!

**Comment by ornelasthiago** [comment]
Hello again!  please, help me! My project its totaly mounted on this theme, but the incompatibility whit the version of moodle make it impossible to implement . Any prev date do publish the stable version compatible whit the moodle 3.2/3.3 + Version? (more to version 3.3). I contributed whit the translation to Brazilian portuguese. I hope this help the development of the project on this language too.  Please give one   date to release! This will save the development of all steps of my project, and my work!  Again, Thanks for this incredible theme . 

Regards.

**Comment by stuartlamour** [comment]
Hi @ornelasthiago,

moodlerooms release open source updates approximately 6 months after the official moodle release to allow for qa, testing, and any bug fixes from moodle core and moodlerooms.

For example the 3.0 release was early July 2016, and the 3.1 release was late December 2016.

The 3.2 release is currently is currently available here https://github.com/moodlerooms/moodle-theme_snap/tree/MOODLE_32_STABLE and will be updated as we push changes.

The 3.3 release will be available in late December 2017.

The 3.4 release will be available in summer 2018, and 3.5 in December 2018 etc...

Hope this helps clarify the timeline for development and releases.

For the bug reported: 

Unfortunately i'm unable to replicate it in the 3.1 or 3.2 release, running on moodle 3.1 and 3.2 respectively. 

Are there any errors showing in the console log or on the page when debugging is on that might give more clues?

**Comment by ornelasthiago** [comment]
Thanks alot!


Regards!



Att...



Thiago Ornelas

2017-07-17 9:17 GMT-03:00 Stuart Lamour <notifications@github.com>:

**Comment by jesmarquez** [comment]
Hi, 

I have sample problem!
I did migration version from 3.1 to 3.2 and continue the problem.
I did installation new moodle 3.2 and add blocks! it work perfect!

This implementation was done over the same server.

**Comment by gthomas2** [comment]
I think we have an issue here - we didn't upgrade our version.php to have a 'requires' property for 3.2

**Comment by jesmarquez** [comment]
The migration I did were moodle site full! Moodle 3.1 with SNAP version 3.1 to Moodle 3.2 with SNAP 3.2 and I dont work!
