### ISSUE TITLE
Video not displaying correctly

### ISSUE THREAD

**Issue by mkeenan750** [moodlerooms/moodle-theme_snap#73]
Hi gthomas2,

thanks for your response, I have updated and all fixed.

I know that the stable release doesn't support yet, 3.2.3 but I was wondering if there was a fix coming related to video, I have embedded a youtube video and it appears and I can press play but the controls and video in all devices dosen't work correctly, in mobile or tablet it plays, desktop it does audio only, and in all devices there is a loading icon even when the clip is playing, (see screenshot, taken on desktop, audio is playing no visual moving) https://ibb.co/ecLtJF

I just have seen comments on web relating to snap and video, so I really want to make sure your theme is able to display video well.

Any feedback would be appreciated.

**Comment by stuartlamour** [comment]
hi @mkeenan750,

the new 3.2 video filter and the 3.2 oembed filter will both be supported in the 3.2 release. 

Cheers
Stuart
