### ISSUE TITLE
No sections visible on moodle 3.3+

### ISSUE THREAD

**Issue by fxpar** [moodlerooms/moodle-theme_snap#77]
Hi,

Thank you for this awesome theme.
I hope you will upgrade to be compatible with newer versions of moodle.

Just for information, I tried it on my moodle 3.3+. Unfortunately, the sections (topics) of the course are not visible. 
I tried creating new ones and changing the Course format without any success. Only the main / default section is visible, no navigation and no display of other sections.

![screen_20170716_121115](https://user-images.githubusercontent.com/11584406/28246693-14f40646-6a20-11e7-92bd-fa8664258c16.png)

Best regards
François

**Comment by fxpar** [comment]
Forgot to tell, it's the github version that I tried.
François

**Comment by stuartlamour** [comment]
Hi @fxpar 

currently the highest version of Moodle Snap supports Moodle 3.2.

Once we begin work on the 3.3 version we will be updating the github branch with work in progress, and a full release of Snap 3.3 for Moodle 3.3 is scheduled for late December of 2017.

Best regards
Stuart Lamour
