### ISSUE TITLE
References to local_pld plugin

### ISSUE THREAD

**Issue by aspark21** [moodlerooms/moodle-theme_snap#8]
will this pld plugin be made available? Is this how one uploads the background picture for the course?

![screen shot 2015-05-29 at 09 40 44](https://cloud.githubusercontent.com/assets/4015496/7879263/d7a13c9a-05e6-11e5-84e0-45f12bae1d05.png)

**Comment by stuartlamour** [comment]
Hi Alister - PLD is Moodlerooms Personalised Learning Designer http://kb.moodlerooms.com/article/81/administrator
In Snap you add a course image in the course summary file.
