### ISSUE TITLE
Featured courses

### ISSUE THREAD

**Issue by carestrepo** [moodlerooms/moodle-theme_snap#80]
hi,

I have an issue with the featured courses, i have one course that I need all can see but when I configure the featured course 1, I can't see the course as student in the front page.

could you help me thanks.

**Comment by davidscotson** [comment]
The code shouldn't care if you are a student or not, are you saying it shows up for admin accounts but not students?

Is it one particular course that doesn't show up. Or do no courses work?

**Comment by carestrepo** [comment]
Hi, thanks for answer

The idea is students can see some general courses, but when I set the featured courses. 

Nobody, teachers, students even administrator  can't see nothing, I need to know if I am missing something in configuration or  isn't working that option in theme snap.

Thanks for your help

**Comment by davidscotson** [comment]
It should be working . When the ids numbers (from the course table in the DB, also seen in the view.php url) of courses are added in the Snap settings, those courses will show up for all users, near the top of the front page. This is seperate from the other lists of courses that can show up on the front page (e.g. enrolled courses or all courses)

**Comment by davidscotson** [comment]
It should be working . When the ids numbers (from the course table in the DB, also seen in the view.php url) of courses are added in the Snap settings, those courses will show up for all users, near the top of the front page. This is seperate from the other lists of courses that can show up on the front page (e.g. enrolled courses or all courses)

**Comment by carestrepo** [comment]
Thanks for the answer.

We installed Moodle in a new server and it's working perfect, may be was a personalized configuration. 

Thanks
