### ISSUE TITLE
Snap CSS doesn't load

### ISSUE THREAD

**Issue by AryanShadowhunter** [moodlerooms/moodle-theme_snap#82]
After activating snap theme there is nothing but pure HTML and no CSS loads.
With checking stylesheets load details, I saw that the CSS located in:
http://_website.domain_/theme/styles.php/snap/1500958652/all
is not loading. I've opened a tab and entered the url; The content was HTML instead of CSS with this message:
**Exception - Undefined variable $fa-var-angle-down: line: 221**

Is there any way to fix this issue?

**Comment by davidscotson** [comment]
That $fa-var-angle-down looks like the name of a Font-Awesome icon. Do you have any settings, plugins or customisations that use that icon font?

**Comment by AryanShadowhunter** [comment]
No. I've just installed snap theme exactly after installing moodle. I checked snap scss folder for main style files. They try to import 'bootstrap/bootstrap' styles, but there are not any folder named 'bootstrap' or 'moodle' in scss folder.

**Comment by davidscotson** [comment]
Are you running Moodle 3.3? They added Font Awesome to that release. The current latest release of Snap is for 3.2 as we run 6 months behind the bleeding edge of moodle releases, to give everything time to settle down. We've only just begun internal work on 3.3, it will be released around christmas time.

**Comment by AryanShadowhunter** [comment]
Yes my moodle version is 3.3. Thanks for your help. I'll be waiting for your update.

**Comment by davidscotson** [comment]
Thanks, the master branch will probably support 3.3 in a month or so and can be used for testing at that point to help find issues before release.
