### ISSUE TITLE
help bubbles on settings pages cut off at edge of page in larger browser window sizes

### ISSUE THREAD

**Issue by upats** [moodlerooms/moodle-theme_snap#83]
the @media (min-width: 768px) .col-md-4 {width: 33.3%} setting is causing settings pages' help popups to cutoff on the side of the page. See screenshot. Changing to 20% seems to fix it fine. This occurs on setting pages where the collapsible setting categories move to the right-side of the page. Also on pages where there is nothing to pad the left or right side of the page, for example the Side Admin -> Users -> Accounts -> Add New User page

It seems the divs are too wide?

![2017-07-28_12-07-05](https://user-images.githubusercontent.com/7084108/28732667-93d8c912-738d-11e7-8550-eb423fa1abdc.png)
![2017-07-28_12-08-26](https://user-images.githubusercontent.com/7084108/28732666-93d83d1c-738d-11e7-8fd4-b1e4c8f15cfe.png)

**Comment by davidscotson** [comment]
I wonder if switching the side that the pop-up pops up would be a good solution:

core/help_icon.mustache
22:    data-placement="{{#ltr}}right{{/ltr}}{{^ltr}}left{{/ltr}}" data-content="{{text}} {{completedoclink}}"

So swapping 'right' and 'left' in that line.

**Comment by davidscotson** [comment]
top and bottom are other options:

https://v4-alpha.getbootstrap.com/components/popovers/#four-directions

**Comment by davidscotson** [comment]
There's much more precise control available, if you follow the link to the Tether docs in the Bootstrap docs, this is one solution:
data-constraints='[{"to": "scrollParent", "attachment": "together"}]'>

Which will use the default side, but move to any other side to stay on screen. That's almost certainly an improvement, and we can see if there's anything better than that available.

**Comment by davidscotson** [comment]
This should be fixed in the lastest master branch, the help will flip left/right to stay onscreen.
