### ISSUE TITLE
Show resources as cards or lists

### ISSUE THREAD

**Issue by rcaac** [moodlerooms/moodle-theme_snap#85]
Do not change to Table of contents above Although this option comes by default

**Comment by stuartlamour** [comment]
Hi @rcaac,

sounds like you are using quite a recent version of snap - the new course setting page was just updated, https://github.com/moodlerooms/moodle-theme_snap/commit/60e09cdbb9420696a7b1f69e46c5f9401ee94af9 is the pull request for changing the table of contents display.
