### ISSUE TITLE
/message/index.php doesn't go full screen

### ISSUE THREAD

**Issue by Stuboter** [moodlerooms/moodle-theme_snap#87]
The messages page only goes to height 500px, and looking at the CSS, it's a fixed value.

From the class "messages", I see these values:

.messages {
    height: 500px;
    overflow-y: auto;
    overflow-x: hidden;
    -webkit-overflow-scrolling: touch;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    padding: 20px;
}

I have a 3000x2000 display and it looks really bad. I would assume you would still have white space on other monitors too. Anyway to make the height relative?
![capture](https://user-images.githubusercontent.com/17487662/29359358-a96ca378-82c1-11e7-9fb1-1f157859302e.PNG)

**Comment by stuartlamour** [comment]
hi @Stuboter - we are inheriting a lot from core for messages, so not much we can do in a theme i'm afraid. Hopefully as core improve it Snap can benefit too. Putting this in as a bug to moodle core might speed things along.
