### ISSUE TITLE
Snap 3.2.3 (2017063000) not allowing me to "Create learning activity" (CSS is blocked?)

### ISSUE THREAD

**Issue by jjliaw** [moodlerooms/moodle-theme_snap#89]
Loving the newest Snap 3.2.3...however, for one of my courses when I click on "Create learning activity" Snap does not pull up the activity chooser--weird!

I tried to turn off the Activity Chooser in the admin / AJAX settings, but it doesn't make a difference.  Clicking "Create learning activity" in my other courses works just fine--I tried pulling up the Course settings in two windows to compare and they are identical, so I'm not sure what the problem is.

Here is a screen capture video of what the problem "looks like":

https://drive.google.com/file/d/0B7W2PTS398G-aDB1MVJFNWUyLVE/view?usp=sharing

In the first part of the video clip, I am clicking on the "Create learning activity" button in my Physics in the Arts course (waves, sound, light, color, etc.) and nothing is happening--in the second part I switch over to my Traditional Physics course (linear motion, free fall, forces, etc.) and the "Create learning activity" button pulls up the activity chooser as expected.

Any ideas?  For now, I just have to temporarily switch themes to the Clean them in order to add things to my Physics in the Arts class, but it would be nice to not have to do that, and it would confuse non "power" users of Moodle to have to do that.....if you need access to my course to poke around, please let me know....

Thanks for all your help and support!

Regards,

Joe

**Comment by davidscotson** [comment]
Do you have any JS errors on the page? If it works on one page but not another it might be a block or other plugin which is only present on one of the pages. The browser's dev console might show errors to point you in the right direction. If not then adding/deleting things from a copy of the course one by one might narrow it down.

**Comment by jjliaw** [comment]
Hi David:

Thanks for the quick reply….you were right, it was a plugin that was causing some trouble….for some reason the new Stash plugin (which is amazing by the way!) was causing trouble with one of its snippets on the main page as a Label—once I removed it and put it in as a page everything was fine….

Thanks for the great work on Snap—it is a work of art!!!!

Regards,

--Joe


[Liaw-Signature v2] [linkedin] <https://www.linkedin.com/in/jjliaw/>  [flipped]  [FLGI100] <http://www.marketwatch.com/story/flgi-publishes-the-top-100-educators-leading-flipped-learning-in-2017-2017-08-16>

**Comment by davidscotson** [comment]
Thanks for checking that, and for the kind words about Snap, they're much appreciated.
