### ISSUE TITLE
SNAP+Quiz activity

### ISSUE THREAD

**Issue by davidgmitchell** [moodlerooms/moodle-theme_snap#9]
Hi,
When taking quizzes the "Time left" is right at the bottom of the screen, which can mean that is disappears off the screen altogether. This makes this activity unusable for us, when we have timed quizzes.

It would be useful if we could set the location of the timer/ navigation, or if it could be displayed further up the screen by default.

Thanks,
David Mitchell

This shows the "Time left" on a larger screen
![showing](https://cloud.githubusercontent.com/assets/13331398/8671870/850a9cd4-2a20-11e5-9b03-ec4b0f3f0507.PNG)

This shows how easy it is for the timer to disappear entirely
![not showing](https://cloud.githubusercontent.com/assets/13331398/8671869/8508f5d2-2a20-11e5-8459-b36ee9f8b4fd.PNG)

**Comment by davidscotson** [comment]
Would a "floating" tab like this one in the bottom-left corner of the screenshot, that always displayed the time on-screen wherever the user scrolls suit your requirements?
![screen shot 2015-07-14 at 13 06 49](https://cloud.githubusercontent.com/assets/7288187/8672762/5224343e-2a29-11e5-9858-b21165175fcc.png)

The rest of the navigation in this case would remain where it was. Does the quiz navigation being at the bottom also cause issues?

**Comment by davidgmitchell** [comment]
A floating tab would be spot on - would it stick to the bottom of the browser window?

The navigation would be nice, but isn't really that important (for us, at least).

**Comment by davidscotson** [comment]
Yes, the time remaining would be stuck to the bottom-left of the screen, so it would always be visible as the user scrolls up and/or down. We'll hopefully have this solution rolled out soon-ish. I'll update this bug when we know for sure it'll be going live.

I can think of both pros and cons of the navigation being at the top or the bottom, so I think I'll leave it where it is for now.

**Comment by davidgmitchell** [comment]
Brilliant - thank you David. Does this get put into the core Moodlerooms product?

Thinking about it I agree with the navigation being at the bottom. Not essential during quizzes.

**Comment by davidscotson** [comment]
Hi,

the change has passed QA now so for Moodlerooms customers it will be part of the MP1 release, which I think is early August or thereabouts.
