### ISSUE TITLE
Featured courses are not shown

### ISSUE THREAD

**Issue by rcaac** [moodlerooms/moodle-theme_snap#93]
That I have a good day, I am showing the highlighted courses, but it does not show the courses that I selected, change that shows the title of my platform. Why this error?

![screenshot_1](https://user-images.githubusercontent.com/26368050/30876022-e9b03a4e-a2ba-11e7-92cc-88a9f669ea57.png)

![screenshot_2](https://user-images.githubusercontent.com/26368050/30876028-f0252394-a2ba-11e7-8c2f-b0496bbd8d3e.png)

**Comment by gthomas2** [comment]
Course id 1 is generally (though not always) the site id. In Moodle the front page is technically a course with the site id. I don't think we support having the Moodle front page as a featured course. When you say it does not show the courses that you selected, are you using the course ids to select them? To get the course id you can simply open up a course and in the address bar you will see the id against view.php - e.g:

www.mymoodlesite.local/course/view.php?id=333

If you wanted to feature the course with the url above you would put 333 into a 'Featured course' field.

**Comment by rcaac** [comment]
Thanks a lot, I had not considered it that way, one more query, how is it that I manage to configure my main view using snap, everything else I already achieved, I lack the one that indicates the image
![screenshot_1](https://user-images.githubusercontent.com/26368050/30920236-14cd46be-a369-11e7-9d35-46f0ffeeb41f.png)

**Comment by stuartlamour** [comment]
Hi @rcaac, 

the user quotes and additional call to action are just html in the topic area, with some css in the additional css for the background gradient style.

Creating elements like these may be something we add to Snap in the future, but currently not on a roadmap.

Cheers
Stuart
