### ISSUE TITLE
Help!  Cannot edit orphaned sections - Moodle & Snap 3.1

### ISSUE THREAD

**Issue by andrewrowatt** [moodlerooms/moodle-theme_snap#95]
Hi Snap Team!

We are upgrading to Moodle 3.1 and Snap 3.1 however we have noticed an issue.  We have a large set of courses designed using the orphaned section "feature" of Moodle. Unfortunately, there appears no way to edit those sections in the 3.1 Snap theme.  Can you suggest any tweaks to theme to enable those sections to be edited?

Thanks,
    Andrew

**Comment by andrewrowatt** [comment]
@davidscotson - any comment?  This seems like a deliberate design choice?

**Comment by davidscotson** [comment]
Hi sorry I missed this comment when it was originally made as I was on leave.

Yes, the original decision made was to not support this in Snap as it was a bit of a gray area as to whether it was supported by core Moodle or not. I believe originally the core "feature" was more of an oversight and by the time people realised what was happening it was too widely used as a workaround for people to fix it as a bug. I think the current version of Moodle has made this official with some changes to how it is done and work is underway to support this in Snap, so you should be able to use this new official method from the next version onwards. (Though the work is not yet complete and so isn't available on the master branch at the moment).

**Comment by andrewrowatt** [comment]
Thanks @davidscotson
