### ISSUE TITLE
Next Section dont work 

### ISSUE THREAD

**Issue by FinalRule** [moodlerooms/moodle-theme_snap#98]
in Course page the links of next sections dont work at all 
![image](https://user-images.githubusercontent.com/24408774/32234622-013bc662-be66-11e7-928f-5bc907dcd015.png)
even the links of the other sections on top dont work 
![image](https://user-images.githubusercontent.com/24408774/32234706-32d60af2-be66-11e7-9382-de1cbbfa0671.png)

**Comment by davidscotson** [comment]
Hi, the most likely explanation is that something is breaking the javascript on your page, stopping any part of Snap that uses javascript from working as intended.

Do you have any error messages in your browser's javascript console?

You could try it in a totally empty new course to try to narrow down the number of items adding content to the page.

**Comment by FinalRule** [comment]
Thanks ... I will try to make new course 
and this the errors that appear to me 
![image](https://user-images.githubusercontent.com/24408774/32239273-c4379fd6-be72-11e7-99a5-4c27b0962caa.png)

**Comment by FinalRule** [comment]
Thanks for replay ... I found the problem ... it was a plugin called "VM Chat" https://moodle.org/plugins/local_vmchat
when I uninstall it everything work fine
I hope that snap make an update that wont make problem with that plugin cause its really useful 
thanks again

**Comment by davidscotson** [comment]
From the screenshot of your error it seems like the plugin may be rewriting the JS calls that Snap (and potentially other items that use lazy loading) to point to the wrong place. I can't read the full url but it should be something like:

http://joule2.dev/lib/requirejs.php/1508851880/theme_snap/course-lazy.js

And from the little bit of the url I can see in the screenshot it seems like it might have been changed to start with local_vmchat instead, which would lead to the JS not being found and so causing a 404 not found error.

If that's the case then the fix will probably need to be on their side, but let us know if they find out that we're doing something wrong and we'll be happy to fix it.

**Comment by FinalRule** [comment]
I reported that bug to VM_chat developers ... and I will tell them the updates you said ... but until they answer ... could that be fixed to change the url of the js file of VM_chat to not start with js ?

**Comment by davidscotson** [comment]
I'm not familiar enough with vm_chat to say what it's doing, it seems to be a weird error, not something I've encountered before with other plugins. If I'm correct that it's affecting all things using the AMD lazy loading then you might want to try to find other new-ish code in core Moodle that also uses this feature and see if it's breaking that as well. That may motivate them to fix the issue.

Some potential candidates to investigate:

lib/amd/src/chartjs-lazy.js
media/player/videojs/amd/src/Youtube-lazy.js
media/player/videojs/amd/src/video-lazy.js
